require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/useremails", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Useremail. As you add validations to Useremail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Useremail.create! valid_attributes
      get useremails_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      useremail = Useremail.create! valid_attributes
      get useremail_url(useremail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_useremail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      useremail = Useremail.create! valid_attributes
      get edit_useremail_url(useremail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Useremail" do
        expect {
          post useremails_url, params: { useremail: valid_attributes }
        }.to change(Useremail, :count).by(1)
      end

      it "redirects to the created useremail" do
        post useremails_url, params: { useremail: valid_attributes }
        expect(response).to redirect_to(useremail_url(Useremail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Useremail" do
        expect {
          post useremails_url, params: { useremail: invalid_attributes }
        }.to change(Useremail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post useremails_url, params: { useremail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested useremail" do
        useremail = Useremail.create! valid_attributes
        patch useremail_url(useremail), params: { useremail: new_attributes }
        useremail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the useremail" do
        useremail = Useremail.create! valid_attributes
        patch useremail_url(useremail), params: { useremail: new_attributes }
        useremail.reload
        expect(response).to redirect_to(useremail_url(useremail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        useremail = Useremail.create! valid_attributes
        patch useremail_url(useremail), params: { useremail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested useremail" do
      useremail = Useremail.create! valid_attributes
      expect {
        delete useremail_url(useremail)
      }.to change(Useremail, :count).by(-1)
    end

    it "redirects to the useremails list" do
      useremail = Useremail.create! valid_attributes
      delete useremail_url(useremail)
      expect(response).to redirect_to(useremails_url)
    end
  end
end
